/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package form;

import form.dialog.polaganje.PolaganjeForm;
import form.dialog.polaganje.PolaganjeViewForm;
import form.dialog.polaganje.RezultatiPolaganja;
import form.dialog.student.StudentForm;
import form.dialog.student.StudentViewForm;
import form.dialog.test.TestForm;
import form.dialog.test.TestViewForm;
import form.util.FormView;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.net.Socket;
import javax.swing.BorderFactory;
import javax.swing.BoxLayout;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.border.Border;
import login.Login;
import session.LocalStorage;

/**
 *
 * @author Vuk
 */
public class AdminForm extends javax.swing.JFrame {

    /**
     * Creates new form MainForm
     */
    private LocalStorage localStorage = LocalStorage.getInstance();
    public AdminForm() {
        initComponents();
        prepareForm();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblImage = new javax.swing.JLabel();
        btnLogOut = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuStudent = new javax.swing.JMenu();
        menuitemKreirajStudent = new javax.swing.JMenuItem();
        menuItemPretrazivanjeStudenta = new javax.swing.JMenuItem();
        menuTest = new javax.swing.JMenu();
        menuitemKreirajTest = new javax.swing.JMenuItem();
        menuiPretrazivanjeTesta = new javax.swing.JMenuItem();
        menuPolaganje = new javax.swing.JMenu();
        menuitemKreirajPolaganje = new javax.swing.JMenuItem();
        menuitemPretrazivanjePolaganja = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblImage.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        lblImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImage.setIcon(new javax.swing.ImageIcon("C:\\Users\\Vuk\\Downloads\\students-write-a-test-exam-in-a-.jpg")); // NOI18N
        lblImage.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblImage.setMinimumSize(new java.awt.Dimension(340, 300));
        lblImage.setName(""); // NOI18N
        lblImage.setPreferredSize(new java.awt.Dimension(1980, 900));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblImage, javax.swing.GroupLayout.DEFAULT_SIZE, 1065, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblImage, javax.swing.GroupLayout.PREFERRED_SIZE, 596, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        btnLogOut.setText("<-] Odjava");
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });

        menuStudent.setText(" Student");

        menuitemKreirajStudent.setText(" Kreiranje studenta");
        menuitemKreirajStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuitemKreirajStudentActionPerformed(evt);
            }
        });
        menuStudent.add(menuitemKreirajStudent);

        menuItemPretrazivanjeStudenta.setText("Pretrazivanje studenta");
        menuItemPretrazivanjeStudenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemPretrazivanjeStudentaActionPerformed(evt);
            }
        });
        menuStudent.add(menuItemPretrazivanjeStudenta);

        jMenuBar1.add(menuStudent);

        menuTest.setText(" Test");

        menuitemKreirajTest.setText("Kreiranje novog testa");
        menuitemKreirajTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuitemKreirajTestActionPerformed(evt);
            }
        });
        menuTest.add(menuitemKreirajTest);

        menuiPretrazivanjeTesta.setText("Pretrazivanje testa");
        menuiPretrazivanjeTesta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuiPretrazivanjeTestaActionPerformed(evt);
            }
        });
        menuTest.add(menuiPretrazivanjeTesta);

        jMenuBar1.add(menuTest);

        menuPolaganje.setText(" Polaganje");

        menuitemKreirajPolaganje.setText(" Kreiranje novog polaganja");
        menuitemKreirajPolaganje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuitemKreirajPolaganjeActionPerformed(evt);
            }
        });
        menuPolaganje.add(menuitemKreirajPolaganje);

        menuitemPretrazivanjePolaganja.setText(" Pretrazivanje polaganja");
        menuitemPretrazivanjePolaganja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuitemPretrazivanjePolaganjaActionPerformed(evt);
            }
        });
        menuPolaganje.add(menuitemPretrazivanjePolaganja);

        jMenuBar1.add(menuPolaganje);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(btnLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuitemKreirajStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuitemKreirajStudentActionPerformed
        // TODO add your handling code here:
        StudentForm studentDialog = new StudentForm(this,true,FormView.FORM_ADD_MODE);
        if(StudentForm.visibility){
            studentDialog.setVisible(true);
        }
    }//GEN-LAST:event_menuitemKreirajStudentActionPerformed

    private void menuItemPretrazivanjeStudentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemPretrazivanjeStudentaActionPerformed
        // TODO add your handling code here:
        StudentViewForm studentDialog = new StudentViewForm(this, true,0);
        studentDialog.setVisible(true);
    }//GEN-LAST:event_menuItemPretrazivanjeStudentaActionPerformed

    private void menuitemKreirajTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuitemKreirajTestActionPerformed
        // TODO add your handling code here:
        TestForm testDialog = new TestForm(this,true,FormView.FORM_ADD_MODE);
        if(TestForm.visibility){
            testDialog.setVisible(true);
        }
    }//GEN-LAST:event_menuitemKreirajTestActionPerformed

    private void menuiPretrazivanjeTestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuiPretrazivanjeTestaActionPerformed
        // TODO add your handling code here:
        TestViewForm testDialog = new TestViewForm(this,true,0);
        testDialog.setVisible(true);
    }//GEN-LAST:event_menuiPretrazivanjeTestaActionPerformed

    private void menuitemKreirajPolaganjeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuitemKreirajPolaganjeActionPerformed
        // TODO add your handling code here:
        PolaganjeForm polaganjeDialog = new PolaganjeForm(this,true,FormView.FORM_ADD_MODE);
        if(polaganjeDialog.visibility){
            polaganjeDialog.setVisible(true);
        }
    }//GEN-LAST:event_menuitemKreirajPolaganjeActionPerformed

    private void menuitemPretrazivanjePolaganjaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuitemPretrazivanjePolaganjaActionPerformed
        // TODO add your handling code here:
        PolaganjeViewForm polaganjeDialog = new PolaganjeViewForm(this,true,0);
        polaganjeDialog.setVisible(true);
    }//GEN-LAST:event_menuitemPretrazivanjePolaganjaActionPerformed

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        // TODO add your handling code here:
        Login login = new Login();
        this.dispose();
        login.setLocationRelativeTo(null);
        login.setVisible(true);
    }//GEN-LAST:event_btnLogOutActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogOut;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblImage;
    private javax.swing.JMenuItem menuItemPretrazivanjeStudenta;
    private javax.swing.JMenu menuPolaganje;
    private javax.swing.JMenu menuStudent;
    private javax.swing.JMenu menuTest;
    private javax.swing.JMenuItem menuiPretrazivanjeTesta;
    private javax.swing.JMenuItem menuitemKreirajPolaganje;
    private javax.swing.JMenuItem menuitemKreirajStudent;
    private javax.swing.JMenuItem menuitemKreirajTest;
    private javax.swing.JMenuItem menuitemPretrazivanjePolaganja;
    // End of variables declaration//GEN-END:variables

    private void prepareForm() {
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        lblImage.setPreferredSize(new Dimension(1980,700));
        jPanel1.setPreferredSize(new Dimension(1980,700));
        jPanel1.setMinimumSize(new Dimension(220,220));
        jPanel1.setMaximumSize(new Dimension(2000,900));
        jPanel1.setLayout(new BoxLayout(jPanel1, BoxLayout.LINE_AXIS));
        //jPanel1.setLayout(null);
    }

}
